### PR TITLE
[Merged by Bors] - Multiple routes

### PR DESCRIPTION
**Pull request by Muqito**
- Add a macro named `routes` to ease chaining filters.

### CODE REVIEW

**Comment by kdy1** [comment]
Please ping me when you are done with it

**Comment by Muqito** [comment]
@kdy1 Depends on how much we wanna do with it. For now it works for the most basic usecases.

Ex.
Chaining like so:

```
let routes = routes![hi, ping];
```

yields

```
hi().or(ping())
```

**Comment by kdy1** [comment]
@Muqito I think we need to consider `#[data]`. Sometimes, a user may want to inject stuff like db.

**Comment by Muqito** [comment]
@kdy1 So I could just use a third arm which would inject the data. I'll get on it

**Comment by Muqito** [comment]
@kdy1 What do you think? :)

**Comment by kdy1** [comment]
Yes. It looks great. Can you document it?

**Pull request closed without merging**
